'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const crypto=require('node:crypto');
const {Server,utils}=require('ssh2');
const engine=require('../build/sftp/engine');
test('SFTP wire: password authentication, list, upload, temp rename, download and delete', {timeout:30000}, async t=>{
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'devkit-ssh-'));
  const local=path.join(root,'local'),remote=path.join(root,'remote');fs.mkdirSync(local);fs.mkdirSync(remote);
  const hostKey=crypto.generateKeyPairSync('rsa',{modulusLength:2048}).privateKey.export({type:'pkcs1',format:'pem'});
  const clients=new Set();const {STATUS_CODE,OPEN_MODE}=utils.sftp;
  const server=new Server({hostKeys:[hostKey]},client=>{
    clients.add(client);client.on('close',()=>clients.delete(client));client.on('error',()=>{});
    client.on('authentication',ctx=>ctx.method==='password' && ctx.username==='fixture' && ctx.password==='test-password'?ctx.accept():ctx.reject());
    client.on('ready',()=>client.on('session',accept=>accept().on('sftp',accept=>{
      const sftp=accept(),handles=new Map();let id=0;
      const resolve=p=>{const target=path.resolve(remote,'.'+p);if(!target.startsWith(remote+path.sep)&&target!==remote)throw new Error('outside fixture');return target;};
      const attrs=s=>({mode:s.mode,size:s.size,uid:0,gid:0,atime:Math.floor(s.atimeMs/1000),mtime:Math.floor(s.mtimeMs/1000)});
      const guard=fn=>(request,...args)=>{try{fn(request,...args);}catch(e){sftp.status(request,e.code==='ENOENT'?STATUS_CODE.NO_SUCH_FILE:STATUS_CODE.FAILURE,e.message);}};
      const handle=value=>{const h=Buffer.alloc(4);h.writeUInt32BE(++id);handles.set(h.toString('hex'),value);return h;};
      for(const name of ['STAT','LSTAT'])sftp.on(name,guard((req,p)=>sftp.attrs(req,attrs(fs.statSync(resolve(p))))));
      sftp.on('REALPATH',guard((req,p)=>sftp.name(req,[{filename:p,longname:p,attrs:{}}])));
      sftp.on('OPENDIR',guard((req,p)=>sftp.handle(req,handle({dir:resolve(p)}))));
      sftp.on('READDIR',guard((req,h)=>{const v=handles.get(h.toString('hex'));if(v.read)return sftp.status(req,STATUS_CODE.EOF);v.read=true;sftp.name(req,fs.readdirSync(v.dir).map(name=>({filename:name,longname:name,attrs:attrs(fs.statSync(path.join(v.dir,name)))})));}));
      sftp.on('OPEN',guard((req,p,flags)=>{const f=flags & OPEN_MODE.WRITE?'w':'r';sftp.handle(req,handle({fd:fs.openSync(resolve(p),f)}));}));
      sftp.on('FSTAT',guard((req,h)=>sftp.attrs(req,attrs(fs.fstatSync(handles.get(h.toString('hex')).fd)))));
      sftp.on('READ',guard((req,h,offset,len)=>{const data=Buffer.alloc(len),n=fs.readSync(handles.get(h.toString('hex')).fd,data,0,len,offset);if(n)sftp.data(req,data.subarray(0,n));else sftp.status(req,STATUS_CODE.EOF);}));
      sftp.on('WRITE',guard((req,h,offset,data)=>{fs.writeSync(handles.get(h.toString('hex')).fd,data,0,data.length,offset);sftp.status(req,STATUS_CODE.OK);}));
      sftp.on('CLOSE',guard((req,h)=>{const v=handles.get(h.toString('hex'));if(v.fd!==undefined)fs.closeSync(v.fd);handles.delete(h.toString('hex'));sftp.status(req,STATUS_CODE.OK);}));
      sftp.on('FSETSTAT',guard((req,h,a)=>{if(a.atime!==undefined)fs.futimesSync(handles.get(h.toString('hex')).fd,a.atime,a.mtime);sftp.status(req,STATUS_CODE.OK);}));
      sftp.on('SETSTAT',guard((req,p,a)=>{if(a.atime!==undefined)fs.utimesSync(resolve(p),a.atime,a.mtime);sftp.status(req,STATUS_CODE.OK);}));
      sftp.on('MKDIR',guard((req,p)=>{fs.mkdirSync(resolve(p));sftp.status(req,STATUS_CODE.OK);}));
      sftp.on('REMOVE',guard((req,p)=>{fs.unlinkSync(resolve(p));sftp.status(req,STATUS_CODE.OK);}));
      sftp.on('RMDIR',guard((req,p)=>{fs.rmdirSync(resolve(p));sftp.status(req,STATUS_CODE.OK);}));
      sftp.on('RENAME',guard((req,a,b)=>{fs.renameSync(resolve(a),resolve(b));sftp.status(req,STATUS_CODE.OK);}));
      sftp.on('EXTENDED',(req)=>sftp.status(req,STATUS_CODE.OP_UNSUPPORTED));
      sftp.on('close',()=>{for(const value of handles.values())if(value.fd!==undefined)try{fs.closeSync(value.fd);}catch{};});
    })));
  });
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  const session=engine.createSession(local,{host:'127.0.0.1',port:server.address().port,username:'fixture',password:'test-password',remotePath:'/',useTempFile:true});
  t.after(async()=>{session.service.dispose();for(const client of clients)client.end();await new Promise(resolve=>server.close(resolve));fs.rmSync(root,{recursive:true,force:true});});
  fs.writeFileSync(path.join(local,'wire.txt'),'over SSH');
  await engine.operate(session,'upload','wire.txt');assert.equal(fs.readFileSync(path.join(remote,'wire.txt'),'utf8'),'over SSH');
  assert.equal((await engine.operate(session,'list')).some(item=>item.name==='wire.txt'),true);
  fs.writeFileSync(path.join(remote,'wire.txt'),'server change');await engine.operate(session,'download','wire.txt');assert.equal(fs.readFileSync(path.join(local,'wire.txt'),'utf8'),'server change');
  await engine.operate(session,'delete','wire.txt',{yes:true});assert.equal(fs.existsSync(path.join(remote,'wire.txt')),false);
});
