// Adapted from ng-jk/vscode-sftp; static imports replace webpack require.context.
import { registerCommand } from './host';
import { createCommand, createFileCommand, createFileMultiCommand } from './commands/abstract/createCommand';
import command0 from './commands/commandCancelAllTransfer';
import command1 from './commands/commandConfig';
import command2 from './commands/commandListActiveFolder';
import command3 from './commands/commandOpenSshConnection';
import command4 from './commands/commandSetProfile';
import command5 from './commands/commandToggleOutputPanel';
import command6 from './commands/commandUploadChangedFiles';
import command7 from './commands/commandUploadFileChanged';
import command8 from './commands/fileCommandCreateFile';
import command9 from './commands/fileCommandCreateFolder';
import command10 from './commands/fileCommandDeleteRemote';
import command11 from './commands/fileCommandDiff';
import command12 from './commands/fileCommandDiffActiveFile';
import command13 from './commands/fileCommandDownload';
import command14 from './commands/fileCommandDownloadActiveFile';
import command15 from './commands/fileCommandDownloadActiveFolder';
import command16 from './commands/fileCommandDownloadFile';
import command17 from './commands/fileCommandDownloadFolder';
import command18 from './commands/fileCommandDownloadForce';
import command19 from './commands/fileCommandDownloadProject';
import command20 from './commands/fileCommandEditInLocal';
import command21 from './commands/fileCommandList';
import command22 from './commands/fileCommandListAll';
import command23 from './commands/fileCommandRevealInExplorer';
import command24 from './commands/fileCommandRevealInRemoteExplorer';
import command25 from './commands/fileCommandSyncBothDirections';
import command26 from './commands/fileCommandSyncLocalToRemote';
import command27 from './commands/fileCommandSyncRemoteToLocal';
import command28 from './commands/fileCommandUpload';
import command29 from './commands/fileCommandUploadActiveFile';
import command30 from './commands/fileCommandUploadActiveFolder';
import command31 from './commands/fileCommandUploadFile';
import command32 from './commands/fileCommandUploadFolder';
import command33 from './commands/fileCommandUploadForce';
import command34 from './commands/fileCommandUploadProject';
import command35 from './commands/fileMultiCommandUploadActiveFileToAllProfiles';
import command36 from './commands/fileMultiCommandUploadActiveFolderToAllProfiles';
import command37 from './commands/fileMultiCommandUploadFileToAllProfiles';
import command38 from './commands/fileMultiCommandUploadFolderToAllProfiles';
import command39 from './commands/fileMultiCommandUploadForceToAllProfiles';
import command40 from './commands/fileMultiCommandUploadProjectToAllProfiles';
import command41 from './commands/fileMultiCommandUploadToAllProfiles';
function register(option: any, creator: any, context: any) {
 option.name = option.id; const Command = creator(option); const instance = new Command();
 registerCommand(context, option.id, instance.run, instance);
}
export default function init(context: any) {
  register(command0, createCommand, context);
  register(command1, createCommand, context);
  register(command2, createCommand, context);
  register(command3, createCommand, context);
  register(command4, createCommand, context);
  register(command5, createCommand, context);
  register(command6, createCommand, context);
  register(command7, createCommand, context);
  register(command8, createFileCommand, context);
  register(command9, createFileCommand, context);
  register(command10, createFileCommand, context);
  register(command11, createFileCommand, context);
  register(command12, createFileCommand, context);
  register(command13, createFileCommand, context);
  register(command14, createFileCommand, context);
  register(command15, createFileCommand, context);
  register(command16, createFileCommand, context);
  register(command17, createFileCommand, context);
  register(command18, createFileCommand, context);
  register(command19, createFileCommand, context);
  register(command20, createFileCommand, context);
  register(command21, createFileCommand, context);
  register(command22, createFileCommand, context);
  register(command23, createFileCommand, context);
  register(command24, createFileCommand, context);
  register(command25, createFileCommand, context);
  register(command26, createFileCommand, context);
  register(command27, createFileCommand, context);
  register(command28, createFileCommand, context);
  register(command29, createFileCommand, context);
  register(command30, createFileCommand, context);
  register(command31, createFileCommand, context);
  register(command32, createFileCommand, context);
  register(command33, createFileCommand, context);
  register(command34, createFileCommand, context);
  register(command35, createFileMultiCommand, context);
  register(command36, createFileMultiCommand, context);
  register(command37, createFileMultiCommand, context);
  register(command38, createFileMultiCommand, context);
  register(command39, createFileMultiCommand, context);
  register(command40, createFileMultiCommand, context);
  register(command41, createFileMultiCommand, context);
}
